import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { fetchCurrentUser } from "@/lib/auth";
import { AuthProvider } from "@/context/auth-context";
import { UserProvider } from "@/context/user-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This controls the list of material symbols to be loaded from google fonts api
// When needing to use a symbol somewhere in the app, add it first here
// Only works when in alphabetical order so maybe sort them in href
const iconList = ["error"];


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchCurrentUser();

  console.log('Logged in user:', user);
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          
          href={`https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=${iconList.sort().join(",")}&display=block`}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider currentUser={user}>
          <AuthProvider token={user?.token}>
            {children}
          </AuthProvider>
        </UserProvider>
      </body>
    </html>
  );
}
